import { useState, type ReactNode } from 'react'
import { DetailToggle } from '../components/DetailToggle'
import { explainIcdCode, explainLabFlag, isCriticalLabFlag } from '../labels'
import type { PatientData } from '../types'

export function SummaryTab({ patient }: { patient: PatientData }) {
  const [technical, setTechnical] = useState(false)
  const s = patient.summary
  const cs = s.clinical_summary

  return (
    <div className="mx-auto max-w-3xl space-y-8 p-6">
      <div className="flex items-center justify-between">
        <h2 className="font-serif text-lg text-ink">Summary</h2>
        <DetailToggle technical={technical} onChange={setTechnical} label="Show full clinical detail" />
      </div>

      {/* Plain-language summary — always shown */}
      <p className="text-sm leading-relaxed text-ink/85">
        {cs?.patient_facing_summary || cs?.chief_complaint || s.summary_narrative || 'No summary available yet.'}
      </p>

      {/* Key concerns — the one thing that always matters, kept visible */}
      {cs?.key_concerns && cs.key_concerns.length > 0 && (
        <Section title="Key concerns" tone="caution">
          <ul className="space-y-1.5 text-sm text-ink/85">
            {cs.key_concerns.map((c, i) => (
              <li key={i} className="border-l-2 border-caution pl-3">
                {c}
              </li>
            ))}
          </ul>
        </Section>
      )}

      {cs?.follow_up_actions && cs.follow_up_actions.length > 0 && (
        <Section title="What happens next">
          <ul className="space-y-1.5 text-sm text-ink/85">
            {cs.follow_up_actions.map((a, i) => (
              <li key={i} className="border-l-2 border-rule pl-3">
                {a}
              </li>
            ))}
          </ul>
        </Section>
      )}

      {/* Always-visible scannable facts, one section at a time */}
      <FactSection title="Diagnoses" count={s.diagnoses?.length}>
        {(s.diagnoses || []).map((dx, i) => {
          const hint = explainIcdCode(dx.icd_code)
          return (
            <div key={i} className="flex items-start justify-between gap-3 border-b border-rule py-2 last:border-0">
              <div>
                <div className="text-sm font-medium text-ink">{dx.name}</div>
                {hint && <div className="text-xs text-ink/50">{hint}</div>}
              </div>
              <span className="shrink-0 text-xs text-ink/50">{dx.status}</span>
            </div>
          )
        })}
      </FactSection>

      <FactSection title="Medications" count={s.medications?.length}>
        {(s.medications || []).map((m, i) => (
          <div key={i} className="flex items-baseline justify-between gap-3 border-b border-rule py-2 last:border-0 text-sm">
            <span className="font-medium text-ink">{m.name}</span>
            <span className="flex divide-x divide-rule text-ink/55">
              <span className="pr-2">{m.dose}</span>
              <span className="pl-2">{m.frequency}</span>
            </span>
          </div>
        ))}
      </FactSection>

      <FactSection title="Recent labs" count={s.lab_results?.length}>
        {(s.lab_results || []).map((l, i) => {
          const critical = isCriticalLabFlag(l.flag)
          return (
            <div key={i} className="flex items-center justify-between gap-3 border-b border-rule py-2 last:border-0 text-sm">
              <span className="text-ink/85">{l.test_name}</span>
              <span className="flex items-baseline gap-2">
                <span className={critical ? 'font-medium text-critical' : 'text-ink/70'}>
                  {l.value} {l.unit}
                </span>
                <span className={`text-xs ${critical ? 'text-critical' : 'text-ink/45'}`}>{explainLabFlag(l.flag)}</span>
              </span>
            </div>
          )
        })}
      </FactSection>

      {/* Technical view: everything, unfiltered */}
      {technical && (
        <div className="space-y-4 border-t-2 border-accent pt-5">
          <div className="font-mono text-xs text-accent">Full clinical detail</div>

          {cs && (
            <div className="space-y-3 text-sm text-ink/80">
              <TechField label="Chief complaint" value={cs.chief_complaint} />
              <TechField label="History of present illness" value={cs.history_of_present_illness} />
              <TechField label="Clinical assessment" value={cs.clinical_assessment} />
              {cs.model_used && <div className="font-mono text-xs text-ink/35">generated by {cs.model_used}</div>}
            </div>
          )}

          <div>
            <div className="mb-1.5 font-mono text-xs text-ink/50">ICD codes</div>
            <div className="flex flex-wrap gap-x-4 gap-y-1">
              {(s.diagnoses || []).map((dx, i) => (
                <span key={i} className="font-mono text-xs text-ink/70">
                  {dx.icd_code || '—'} {dx.name}
                </span>
              ))}
            </div>
          </div>

          {s.clinical_flags && s.clinical_flags.length > 0 && (
            <div>
              <div className="mb-1.5 font-mono text-xs text-ink/50">Clinical flags</div>
              <ul className="space-y-1 text-sm text-ink/80">
                {s.clinical_flags.map((f, i) => (
                  <li key={i}>{typeof f === 'string' ? f : f.text}</li>
                ))}
              </ul>
            </div>
          )}

          {s.timeline && s.timeline.length > 0 && (
            <div>
              <div className="mb-1.5 font-mono text-xs text-ink/50">Timeline</div>
              <ol className="space-y-1 text-sm text-ink/80">
                {[...s.timeline].reverse().map((t, i) => (
                  <li key={i} className="flex gap-3">
                    <span className="font-mono text-xs text-ink/40">{t.date}</span>
                    <span>{t.event}</span>
                  </li>
                ))}
              </ol>
            </div>
          )}
        </div>
      )}
    </div>
  )
}

function Section({ title, tone, children }: { title: string; tone?: 'caution'; children: ReactNode }) {
  return (
    <div>
      <h3 className={`mb-2 font-serif text-base ${tone === 'caution' ? 'text-caution' : 'text-ink'}`}>{title}</h3>
      {children}
    </div>
  )
}

function FactSection({ title, count, children }: { title: string; count?: number; children: ReactNode }) {
  if (!count) return null
  return (
    <details className="border-t border-rule pt-4" open>
      <summary className="cursor-pointer font-serif text-base text-ink">
        {title} <span className="ml-1 font-mono text-xs text-ink/35">({count})</span>
      </summary>
      <div className="mt-3">{children}</div>
    </details>
  )
}

function TechField({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="font-mono text-xs text-ink/50">{label}</div>
      <p>{value}</p>
    </div>
  )
}
